# Generated by Django 4.2.4 on 2023-08-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.tododetail'),
        ),
    ]
