# Generated by Django 4.2.4 on 2023-08-19 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododetail',
            name='reminder_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 19, 23, 57, 8, 92651)),
            preserve_default=False,
        ),
    ]
